// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Lanchonete.Context;

#nullable disable

namespace Lanchonete.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240526204856_MigracaoInicial")]
    partial class MigracaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Lanchonete.Models.Categoria", b =>
            {
                b.Property<int>("CategoriaID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("CategoriaNome")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Descricao")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.HasKey("CategoriaID");

                b.ToTable("Categorias");
            });

            modelBuilder.Entity("Lanchonete.Models.Lanche", b =>
            {
                b.Property<int>("LancheId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<int>("CategoriaId")
                    .HasColumnType("int");

                b.Property<string>("DescricaoCurta")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("DescricaoDetalhada")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<bool>("EmEstoque")
                    .HasColumnType("bit");

                b.Property<string>("ImagemThumbnailUrl")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("ImagemUrl")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<bool>("IsLanchePreferido")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("nvarchar(80)");

                b.Property<decimal>("Preco")
                    .HasColumnType("decimal(10,2)") // Correto
                    .IsRequired(); // Se for obrigatório

                b.HasKey("LancheId");

                b.HasIndex("CategoriaId");

                b.ToTable("Lanches");
            });

            modelBuilder.Entity("Lanchonete.Models.Lanche", b =>
            {
                b.HasOne("Lanchonete.Models.Categoria", "Categoria")
                    .WithMany("Lanches")
                    .HasForeignKey("CategoriaId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Categoria");
            });

            modelBuilder.Entity("Lanchonete.Models.Categoria", b =>
            {
                b.Navigation("Lanches");
            });
        }
    }
}